In [1]:
import pandas as pd
import os, glob
import csv
  
demo = pd.concat(map(pd.read_csv, glob.glob(os.path.join('merge_datagov/Demography', "demo*.csv"))))

/home/harshitw/anaconda3/envs/685assing1/lib/python3.5/site-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """

In [2]:
demo = demo.fillna(demo.mean())

In [3]:
demo.drop('Country/ States/ Union Territories Name', axis=1)

,Category,Child sex ratio in population (0-6 age group) - Rural - 2001,Child sex ratio in population (0-6 age group) - Rural - 2011,Child sex ratio in population (0-6 age group) - Total - 2001,Child sex ratio in population (0-6 age group) - Total - 2011,Child sex ratio in population (0-6 age group) - Urban - 2001,Child sex ratio in population (0-6 age group) - Urban - 2011,Decadal growth rate - Rural - 1991-01,Decadal growth rate - Rural - 2001-11,Decadal growth rate - Total - 1991-01,Decadal growth rate - Total - 2001-11,Decadal growth rate - Urban - 1991-01,Decadal growth rate - Urban - 2001-11,Sex ratio of total population - Rural - 2001,Sex ratio of total population - Rural - 2011,Sex ratio of total population - Total - 2001,Sex ratio of total population - Total - 2011,Sex ratio of total population - Urban - 2001,Sex ratio of total population - Urban - 2011
0,Country,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,19.200000,12.300000,21.500000,17.700000,32.600000,31.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
1,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,13.900000,1.700000,14.600000,11.000000,16.300000,35.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
2,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,15.400000,22.600000,27.000000,26.000000,106.000000,39.300000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
3,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,16.500000,15.500000,18.900000,17.100000,38.200000,27.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
4,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,28.500000,24.300000,28.600000,25.400000,29.400000,35.400000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
5,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,14.400000,17.800000,18.300000,22.600000,36.600000,41.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
6,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,-1.900000,-18.500000,15.200000,8.200000,39.800000,35.200000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
7,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,17.300000,9.300000,22.700000,19.300000,32.900000,36.000000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
8,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,21.100000,9.800000,28.400000,19.900000,50.800000,44.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
9,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,16.100000,12.700000,17.500000,12.900000,32.600000,15.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
10,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,26.200000,19.400000,29.400000,23.600000,40.300000,36.400000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
11,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,21.800000,19.600000,23.400000,22.400000,29.100000,32.400000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
12,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,12.300000,7.400000,17.500000,15.600000,29.100000,31.500000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
13,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,10.100000,-25.900000,9.400000,4.900000,7.600000,92.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
14,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.300000,18.400000,24.300000,20.300000,30.100000,25.700000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
15,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,15.300000,10.400000,22.700000,16.000000,34.600000,23.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
16,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,29.000000,17.700000,24.900000,24.500000,13.900000,44.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
17,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,29.100000,27.200000,30.700000,27.900000,37.600000,31.100000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
18,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,20.400000,17.400000,28.800000,23.500000,38.700000,29.700000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
19,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,64.500000,-14.600000,64.500000,-0.600000,64.600000,66.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
20,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,14.100000,11.800000,16.300000,14.000000,30.300000,26.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
21,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,12.700000,7.800000,20.100000,13.900000,37.900000,25.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
22,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,27.600000,19.000000,28.400000,21.300000,31.300000,29.000000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
23,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,30.200000,-5.000000,33.100000,12.900000,61.800000,156.500000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
24,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,-5.100000,6.600000,11.700000,15.600000,44.100000,27.000000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
25,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,13.600000,2.200000,16.000000,14.800000,29.400000,76.200000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
26,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,24.100000,18.000000,25.800000,20.200000,33.000000,28.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
27,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,16.500000,11.500000,20.400000,18.800000,33.400000,39.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
28,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,17.000000,7.700000,17.800000,13.800000,19.900000,29.700000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
29,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,16.600000,-1.200000,26.900000,6.900000,55.000000,23.500000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,988.000000,1003.000000,961.000000,973.000000,934.000000,956.000000
7,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,945.000000,949.000000,920.000000,919.000000,880.000000,880.000000
8,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,866.000000,882.000000,861.000000,879.000000,847.000000,873.000000
9,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,989.000000,986.000000,968.000000,972.000000,795.000000,853.000000
10,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,917.000000,908.000000,892.000000,889.000000,819.000000,840.000000
11,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,962.000000,961.000000,941.000000,948.000000,870.000000,910.000000
12,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,977.000000,979.000000,965.000000,973.000000,942.000000,963.000000
13,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,1059.000000,1078.000000,1058.000000,1084.000000,1058.000000,1091.000000
14,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,927.000000,936.000000,919.000000,931.000000,898.000000,918.000000
15,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,960.000000,952.000000,922.000000,929.000000,873.000000,903.000000
16,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,967.000000,969.000000,978.000000,985.000000,1009.000000,1026.000000
17,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,969.000000,986.000000,972.000000,989.000000,982.000000,1001.000000
18,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,923.000000,952.000000,935.000000,976.000000,948.000000,998.000000
19,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,916.000000,940.000000,900.000000,931.000000,829.000000,908.000000
20,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,987.000000,989.000000,972.000000,979.000000,895.000000,932.000000
21,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,890.000000,907.000000,876.000000,895.000000,849.000000,875.000000
22,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,930.000000,933.000000,921.000000,928.000000,890.000000,914.000000
23,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,880.000000,882.000000,875.000000,890.000000,830.000000,913.000000
24,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,992.000000,993.000000,987.000000,996.000000,982.000000,1000.000000
25,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,946.000000,955.000000,948.000000,960.000000,959.000000,973.000000
26,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,904.000000,918.000000,898.000000,912.000000,876.000000,894.000000
27,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,1007.000000,1000.000000,962.000000,963.000000,845.000000,884.000000
28,State,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,950.000000,953.000000,934.000000,950.000000,893.000000,944.000000
29,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,861.000000,877.000000,846.000000,876.000000,815.000000,874.000000
30,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,621.000000,690.000000,777.000000,818.000000,796.000000,822.000000
31,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,852.000000,863.000000,812.000000,774.000000,691.000000,682.000000
32,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,586.000000,864.000000,710.000000,618.000000,984.000000,551.000000
33,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,959.000000,952.000000,948.000000,946.000000,935.000000,945.000000
34,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,810.000000,852.000000,821.000000,868.000000,822.000000,868.000000
35,Union Territory,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,990.000000,1028.000000,1001.000000,1037.000000,1007.000000,1042.000000

In [5]:
demo.drop('Category', axis=1)

,Child sex ratio in population (0-6 age group) - Rural - 2001,Child sex ratio in population (0-6 age group) - Rural - 2011,Child sex ratio in population (0-6 age group) - Total - 2001,Child sex ratio in population (0-6 age group) - Total - 2011,Child sex ratio in population (0-6 age group) - Urban - 2001,Child sex ratio in population (0-6 age group) - Urban - 2011,Country/ States/ Union Territories Name,Decadal growth rate - Rural - 1991-01,Decadal growth rate - Rural - 2001-11,Decadal growth rate - Total - 1991-01,Decadal growth rate - Total - 2001-11,Decadal growth rate - Urban - 1991-01,Decadal growth rate - Urban - 2001-11,Sex ratio of total population - Rural - 2001,Sex ratio of total population - Rural - 2011,Sex ratio of total population - Total - 2001,Sex ratio of total population - Total - 2011,Sex ratio of total population - Urban - 2001,Sex ratio of total population - Urban - 2011
0,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,INDIA,19.200000,12.300000,21.500000,17.700000,32.600000,31.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
1,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Andhra Pradesh,13.900000,1.700000,14.600000,11.000000,16.300000,35.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
2,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Arunachal Pradesh,15.400000,22.600000,27.000000,26.000000,106.000000,39.300000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
3,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Assam,16.500000,15.500000,18.900000,17.100000,38.200000,27.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
4,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Bihar,28.500000,24.300000,28.600000,25.400000,29.400000,35.400000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
5,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Chhattisgarh,14.400000,17.800000,18.300000,22.600000,36.600000,41.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
6,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Goa,-1.900000,-18.500000,15.200000,8.200000,39.800000,35.200000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
7,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Gujarat,17.300000,9.300000,22.700000,19.300000,32.900000,36.000000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
8,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Haryana,21.100000,9.800000,28.400000,19.900000,50.800000,44.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
9,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Himachal Pradesh,16.100000,12.700000,17.500000,12.900000,32.600000,15.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
10,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Jammu & Kashmir,26.200000,19.400000,29.400000,23.600000,40.300000,36.400000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
11,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Jharkhand,21.800000,19.600000,23.400000,22.400000,29.100000,32.400000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
12,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Karnataka,12.300000,7.400000,17.500000,15.600000,29.100000,31.500000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
13,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Kerala,10.100000,-25.900000,9.400000,4.900000,7.600000,92.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
14,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Madhya Pradesh,22.300000,18.400000,24.300000,20.300000,30.100000,25.700000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
15,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Maharashtra,15.300000,10.400000,22.700000,16.000000,34.600000,23.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
16,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Manipur,29.000000,17.700000,24.900000,24.500000,13.900000,44.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
17,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Meghalaya,29.100000,27.200000,30.700000,27.900000,37.600000,31.100000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
18,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Mizoram,20.400000,17.400000,28.800000,23.500000,38.700000,29.700000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
19,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Nagaland,64.500000,-14.600000,64.500000,-0.600000,64.600000,66.600000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
20,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Odisha,14.100000,11.800000,16.300000,14.000000,30.300000,26.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
21,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Punjab,12.700000,7.800000,20.100000,13.900000,37.900000,25.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
22,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Rajasthan,27.600000,19.000000,28.400000,21.300000,31.300000,29.000000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
23,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Sikkim,30.200000,-5.000000,33.100000,12.900000,61.800000,156.500000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
24,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Tamil Nadu,-5.100000,6.600000,11.700000,15.600000,44.100000,27.000000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
25,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Tripura,13.600000,2.200000,16.000000,14.800000,29.400000,76.200000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
26,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Uttar Pradesh,24.100000,18.000000,25.800000,20.200000,33.000000,28.800000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
27,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Uttarakhand,16.500000,11.500000,20.400000,18.800000,33.400000,39.900000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
28,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,West Bengal,17.000000,7.700000,17.800000,13.800000,19.900000,29.700000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
29,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,A & N Islands,16.600000,-1.200000,26.900000,6.900000,55.000000,23.500000,923.527778,942.138889,920.194444,931.361111,891.916667,912.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Goa,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,988.000000,1003.000000,961.000000,973.000000,934.000000,956.000000
7,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Gujarat,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,945.000000,949.000000,920.000000,919.000000,880.000000,880.000000
8,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Haryana,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,866.000000,882.000000,861.000000,879.000000,847.000000,873.000000
9,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Himachal Pradesh,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,989.000000,986.000000,968.000000,972.000000,795.000000,853.000000
10,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Jammu & Kashmir,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,917.000000,908.000000,892.000000,889.000000,819.000000,840.000000
11,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Jharkhand,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,962.000000,961.000000,941.000000,948.000000,870.000000,910.000000
12,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Karnataka,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,977.000000,979.000000,965.000000,973.000000,942.000000,963.000000
13,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Kerala,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,1059.000000,1078.000000,1058.000000,1084.000000,1058.000000,1091.000000
14,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Madhya Pradesh,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,927.000000,936.000000,919.000000,931.000000,898.000000,918.000000
15,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Maharashtra,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,960.000000,952.000000,922.000000,929.000000,873.000000,903.000000
16,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Manipur,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,967.000000,969.000000,978.000000,985.000000,1009.000000,1026.000000
17,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Meghalaya,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,969.000000,986.000000,972.000000,989.000000,982.000000,1001.000000
18,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Mizoram,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,923.000000,952.000000,935.000000,976.000000,948.000000,998.000000
19,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Nagaland,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,916.000000,940.000000,900.000000,931.000000,829.000000,908.000000
20,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Odisha,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,987.000000,989.000000,972.000000,979.000000,895.000000,932.000000
21,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Punjab,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,890.000000,907.000000,876.000000,895.000000,849.000000,875.000000
22,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Rajasthan,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,930.000000,933.000000,921.000000,928.000000,890.000000,914.000000
23,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Sikkim,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,880.000000,882.000000,875.000000,890.000000,830.000000,913.000000
24,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Tamil Nadu,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,992.000000,993.000000,987.000000,996.000000,982.000000,1000.000000
25,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Tripura,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,946.000000,955.000000,948.000000,960.000000,959.000000,973.000000
26,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Uttar Pradesh,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,904.000000,918.000000,898.000000,912.000000,876.000000,894.000000
27,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Uttarakhand,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,1007.000000,1000.000000,962.000000,963.000000,845.000000,884.000000
28,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,West Bengal,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,950.000000,953.000000,934.000000,950.000000,893.000000,944.000000
29,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,A & N Islands,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,861.000000,877.000000,846.000000,876.000000,815.000000,874.000000
30,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Chandigarh,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,621.000000,690.000000,777.000000,818.000000,796.000000,822.000000
31,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,D & N Haveli,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,852.000000,863.000000,812.000000,774.000000,691.000000,682.000000
32,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Daman & Diu,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,586.000000,864.000000,710.000000,618.000000,984.000000,551.000000
33,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Lakshadweep,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,959.000000,952.000000,948.000000,946.000000,935.000000,945.000000
34,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,NCT of Delhi,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,810.000000,852.000000,821.000000,868.000000,822.000000,868.000000
35,938.166667,927.805556,933.361111,925.666667,914.083333,915.083333,Puducherry,22.202778,2.491667,26.247222,19.247222,43.852778,50.836111,990.000000,1028.000000,1001.000000,1037.000000,1007.000000,1042.000000

In [8]:
max = demo.describe().iloc[7:8,:]
min = demo.describe().iloc[3:4,:]
min

,Child sex ratio in population (0-6 age group) - Rural - 2001,Child sex ratio in population (0-6 age group) - Rural - 2011,Child sex ratio in population (0-6 age group) - Total - 2001,Child sex ratio in population (0-6 age group) - Total - 2011,Child sex ratio in population (0-6 age group) - Urban - 2001,Child sex ratio in population (0-6 age group) - Urban - 2011,Decadal growth rate - Rural - 1991-01,Decadal growth rate - Rural - 2001-11,Decadal growth rate - Total - 1991-01,Decadal growth rate - Total - 2001-11,Decadal growth rate - Urban - 1991-01,Decadal growth rate - Urban - 2001-11,Sex ratio of total population - Rural - 2001,Sex ratio of total population - Rural - 2011,Sex ratio of total population - Total - 2001,Sex ratio of total population - Total - 2011,Sex ratio of total population - Urban - 2001,Sex ratio of total population - Urban - 2011
min,799.0,814.0,798.0,834.0,796.0,832.0,-5.1,-68.5,9.4,-0.6,-7.4,15.6,586.0,690.0,710.0,618.0,691.0,551.0

In [11]:
for column in demo:
    if column == 'Country/ States/ Union Territories Name':
        continue
    if column == 'Category':
        continue
    else:
       #df[column] = (df[column] - min.iloc[0][column])/(max.iloc[0][column] - min.iloc[0][column])
        demo[column] = demo[column]/max.iloc[0][column]

In [12]:
demo.head()

,Category,Child sex ratio in population (0-6 age group) - Rural - 2001,Child sex ratio in population (0-6 age group) - Rural - 2011,Child sex ratio in population (0-6 age group) - Total - 2001,Child sex ratio in population (0-6 age group) - Total - 2011,Child sex ratio in population (0-6 age group) - Urban - 2001,Child sex ratio in population (0-6 age group) - Urban - 2011,Country/ States/ Union Territories Name,Decadal growth rate - Rural - 1991-01,Decadal growth rate - Rural - 2001-11,Decadal growth rate - Total - 1991-01,Decadal growth rate - Total - 2001-11,Decadal growth rate - Urban - 1991-01,Decadal growth rate - Urban - 2001-11,Sex ratio of total population - Rural - 2001,Sex ratio of total population - Rural - 2011,Sex ratio of total population - Total - 2001,Sex ratio of total population - Total - 2011,Sex ratio of total population - Urban - 2001,Sex ratio of total population - Urban - 2011
0,Country,0.935361,0.949647,0.953382,0.952332,0.932738,0.938547,INDIA,0.221709,0.452206,0.333333,0.316637,0.098668,0.145338,0.872075,0.873969,0.869749,0.859189,0.843021,0.836032
1,State,0.935361,0.949647,0.953382,0.952332,0.932738,0.938547,Andhra Pradesh,0.160508,0.062500,0.226357,0.196780,0.049334,0.162706,0.872075,0.873969,0.869749,0.859189,0.843021,0.836032
2,State,0.935361,0.949647,0.953382,0.952332,0.932738,0.938547,Arunachal Pradesh,0.177829,0.830882,0.418605,0.465116,0.320823,0.179616,0.872075,0.873969,0.869749,0.859189,0.843021,0.836032
3,State,0.935361,0.949647,0.953382,0.952332,0.932738,0.938547,Assam,0.190531,0.569853,0.293023,0.305903,0.115617,0.127514,0.872075,0.873969,0.869749,0.859189,0.843021,0.836032
4,State,0.935361,0.949647,0.953382,0.952332,0.932738,0.938547,Bihar,0.329099,0.893382,0.443411,0.454383,0.088983,0.161792,0.872075,0.873969,0.869749,0.859189,0.843021,0.836032

In [13]:
#for column in demo:
#    corr 
#df['A'].corr(df['B'])
demo.corr(method='kendall')

,Child sex ratio in population (0-6 age group) - Rural - 2001,Child sex ratio in population (0-6 age group) - Rural - 2011,Child sex ratio in population (0-6 age group) - Total - 2001,Child sex ratio in population (0-6 age group) - Total - 2011,Child sex ratio in population (0-6 age group) - Urban - 2001,Child sex ratio in population (0-6 age group) - Urban - 2011,Decadal growth rate - Rural - 1991-01,Decadal growth rate - Rural - 2001-11,Decadal growth rate - Total - 1991-01,Decadal growth rate - Total - 2001-11,Decadal growth rate - Urban - 1991-01,Decadal growth rate - Urban - 2001-11,Sex ratio of total population - Rural - 2001,Sex ratio of total population - Rural - 2011,Sex ratio of total population - Total - 2001,Sex ratio of total population - Total - 2011,Sex ratio of total population - Urban - 2001,Sex ratio of total population - Urban - 2011
Child sex ratio in population (0-6 age group) - Rural - 2001,1.000000,0.652370,0.881219,0.735271,0.620668,0.536358,0.031066,-0.043492,0.024860,0.006214,0.062150,0.068365,-0.031066,-0.024876,-0.018651,-0.012428,0.006214,-0.006213
Child sex ratio in population (0-6 age group) - Rural - 2011,0.652370,1.000000,0.755169,0.876904,0.821628,0.645332,0.018636,-0.026091,0.014914,0.003728,0.037284,0.041013,-0.018636,-0.014923,-0.011189,-0.007456,0.003728,-0.003727
Child sex ratio in population (0-6 age group) - Total - 2001,0.881219,0.755169,1.000000,0.848080,0.740246,0.644700,0.031075,-0.043505,0.024868,0.006216,0.062170,0.068387,-0.031075,-0.024883,-0.018657,-0.012432,0.006216,-0.006215
Child sex ratio in population (0-6 age group) - Total - 2011,0.735271,0.876904,0.848080,1.000000,0.846130,0.767988,0.018642,-0.026099,0.014918,0.003729,0.037296,0.041026,-0.018642,-0.014928,-0.011192,-0.007458,0.003729,-0.003728
Child sex ratio in population (0-6 age group) - Urban - 2001,0.620668,0.821628,0.740246,0.846130,1.000000,0.771167,0.018636,-0.026091,0.014914,0.003728,0.037284,0.041013,-0.018636,-0.014923,-0.011189,-0.007456,0.003728,-0.003727
Child sex ratio in population (0-6 age group) - Urban - 2011,0.536358,0.645332,0.644700,0.767988,0.771167,1.000000,-0.006211,0.008696,-0.004970,-0.001242,-0.012426,-0.013669,0.006211,0.004974,0.003729,0.002485,-0.001242,0.001242
Decadal growth rate - Rural - 1991-01,0.031066,0.018636,0.031075,0.018642,0.018636,-0.006211,1.000000,-0.156473,0.517391,0.318274,0.144099,0.404969,0.031046,0.024860,0.018639,0.012420,-0.006210,0.006209
Decadal growth rate - Rural - 2001-11,-0.043492,-0.026091,-0.043505,-0.026099,-0.026091,0.008696,-0.156473,1.000000,-0.194410,0.369197,-0.324845,-0.560870,-0.043465,-0.034804,-0.026095,-0.017389,0.008694,-0.008693
Decadal growth rate - Total - 1991-01,0.024860,0.014914,0.024868,0.014918,0.014914,-0.004970,0.517391,-0.194410,1.000000,0.397888,0.516931,0.239826,0.024845,0.019894,0.014916,0.009939,-0.004970,0.004969
Decadal growth rate - Total - 2001-11,0.006214,0.003728,0.006216,0.003729,0.003728,-0.001242,0.318274,0.369197,0.397888,1.000000,0.051250,-0.063674,0.006210,0.004973,0.003728,0.002484,-0.001242,0.001242
Decadal growth rate - Urban - 1991-01,0.062150,0.037284,0.062170,0.037296,0.037284,-0.012426,0.144099,-0.324845,0.516931,0.051250,1.000000,0.385834,0.062112,0.049736,0.037290,0.024849,-0.012424,0.012422
Decadal growth rate - Urban - 2001-11,0.068365,0.041013,0.068387,0.041026,0.041013,-0.013669,0.404969,-0.560870,0.239826,-0.063674,0.385834,1.000000,0.068323,0.054709,0.041019,0.027333,-0.013667,0.013665
Sex ratio of total population - Rural - 2001,-0.031066,-0.018636,-0.031075,-0.018642,-0.018636,0.006211,0.031046,-0.043465,0.024845,0.006210,0.062112,0.068323,1.000000,0.745184,0.789686,0.636858,0.441857,0.552623
Sex ratio of total population - Rural - 2011,-0.024876,-0.014923,-0.024883,-0.014928,-0.014923,0.004974,0.024860,-0.034804,0.019894,0.004973,0.049736,0.054709,0.745184,1.000000,0.834577,0.878633,0.491375,0.517092
Sex ratio of total population - Total - 2001,-0.018651,-0.011189,-0.018657,-0.011192,-0.011189,0.003729,0.018639,-0.026095,0.014916,0.003728,0.037290,0.041019,0.789686,0.834577,1.000000,0.842939,0.555228,0.671637
Sex ratio of total population - Total - 2011,-0.012428,-0.007456,-0.012432,-0.007458,-0.007456,0.002485,0.012420,-0.017389,0.009939,0.002484,0.024849,0.027333,0.636858,0.878633,0.842939,1.000000,0.601863,0.636237
Sex ratio of total population - Urban - 2001,0.006214,0.003728,0.006216,0.003729,0.003728,-0.001242,-0.006210,0.008694,-0.004970,-0.001242,-0.012424,-0.013667,0.441857,0.491375,0.555228,0.601863,1.000000,0.766651
Sex ratio of total population - Urban - 2011,-0.006213,-0.003727,-0.006215,-0.003728,-0.003727,0.001242,0.006209,-0.008693,0.004969,0.001242,0.012422,0.013665,0.552623,0.517092,0.671637,0.636237,0.766651,1.000000

In [21]:
eco = pd.concat(map(pd.read_csv, glob.glob(os.path.join('merge_datagov/Economy', "eco*.csv"))))
eco = eco.fillna(eco.mean())
eco

/home/harshitw/anaconda3/envs/685assing1/lib/python3.5/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,All_India GDP,All_India NDP,Andaman & Nicobar Islands,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Delhi,...,Puducherry,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal1
0,8.736039e+06,4.946537e+06,3979.000000,379402.00,11063.000000,143175.000000,247144.000000,18768.000000,158074.000000,343767.00,...,16818.00,266628.000000,436465.000000,11165.000000,751485.00,359433.00,19208.000000,7.240490e+05,115523.000000,NaN
1,9.946636e+06,4.946537e+06,4421.000000,411404.00,12547.000000,156864.000000,282368.000000,21609.000000,177511.000000,391238.00,...,18875.00,297734.000000,494004.000000,12338.000000,855481.00,401493.00,21663.000000,8.229030e+05,131835.000000,NaN
2,1.123664e+07,4.946537e+06,5159.000000,464272.00,14602.000000,177745.000000,317101.000000,24787.000000,206690.000000,443783.00,...,21870.00,334714.000000,549701.000000,13862.000000,971090.00,452186.00,25593.000000,9.441460e+05,149817.000000,NaN
3,1.243375e+07,4.946537e+06,5721.000000,526468.00,16761.000000,198098.000000,373920.000000,27844.000000,234982.000000,492424.00,...,24089.00,368011.000000,612194.000000,15209.000000,1092564.00,511178.00,29667.000000,1.043371e+06,161985.000000,NaN
4,1.367533e+07,4.946537e+06,2210.446129,609934.00,18784.000000,224234.000000,413503.000000,30304.000000,260776.000000,551963.00,...,26533.00,148641.196452,244477.200323,16637.000000,1212668.00,575631.00,11342.395161,1.153795e+06,184091.000000,NaN
5,1.525103e+07,4.946537e+06,2210.446129,699307.00,6689.537179,89285.554167,149763.578462,11432.329744,290140.000000,622385.00,...,29557.00,148641.196452,244477.200323,6275.935128,1338766.00,654294.00,11342.395161,4.227932e+05,68082.334359,NaN
6,1.386000e+01,4.946537e+06,11.130000,8.43,13.410000,9.560000,14.250000,15.140000,12.300000,13.81,...,12.23,11.670000,13.180000,10.510000,13.84,11.70,12.780000,1.365000e+01,14.120000,NaN
7,1.297000e+01,4.946537e+06,16.680000,12.85,16.380000,13.310000,12.300000,14.710000,16.440000,13.43,...,15.87,12.420000,11.270000,12.350000,13.51,12.63,18.140000,1.473000e+01,13.640000,NaN
8,1.065000e+01,4.946537e+06,10.890000,13.40,14.790000,11.450000,17.920000,12.330000,13.690000,10.96,...,10.14,9.950000,11.370000,9.720000,12.51,13.05,15.920000,1.051000e+01,8.120000,NaN
9,9.990000e+00,4.946537e+06,2210.446129,15.85,12.070000,13.190000,10.590000,8.840000,10.980000,12.09,...,10.15,148641.196452,244477.200323,9.390000,10.99,12.61,11342.395161,1.058000e+01,13.650000,NaN
10,1.152000e+01,4.946537e+06,2210.446129,14.65,6689.537179,89285.554167,149763.578462,11432.329744,11.260000,12.76,...,11.40,148641.196452,244477.200323,6275.935128,10.40,13.67,11342.395161,4.227932e+05,68082.334359,NaN
0,8.736039e+06,4.946537e+06,3979.000000,379402.00,11063.000000,143175.000000,247144.000000,18768.000000,158074.000000,343767.00,...,16818.00,266628.000000,436465.000000,11165.000000,751485.00,359433.00,19208.000000,7.240490e+05,115524.000000,NaN
1,9.215125e+06,4.946537e+06,4156.000000,380629.00,11299.000000,147342.000000,256851.000000,20265.000000,165937.000000,366538.00,...,17310.00,280823.000000,454987.000000,11421.000000,787907.00,369290.00,20873.000000,7.549280e+05,123891.000000,NaN
2,9.817822e+06,4.946537e+06,4502.000000,407115.00,12348.000000,154525.000000,269650.000000,21893.000000,182229.000000,391718.00,...,19170.00,298581.000000,482605.000000,12114.000000,842182.00,389882.00,22819.000000,8.032330e+05,134089.000000,NaN
3,1.052269e+07,4.946537e+06,4839.000000,441741.00,13541.000000,166709.000000,304766.000000,23920.000000,196023.000000,422920.00,...,20428.00,313276.000000,512095.000000,12882.000000,900628.00,423972.00,25086.000000,8.538720e+05,140791.000000,NaN
4,1.135753e+07,4.946537e+06,2210.446129,490134.00,13963.000000,179595.000000,326535.000000,26379.000000,209012.000000,460217.00,...,22007.00,148641.196452,244477.200323,13722.000000,979816.00,464389.00,11342.395161,9.147480e+05,153041.000000,NaN
5,1.216548e+07,4.946537e+06,2210.446129,547021.00,6689.537179,89285.554167,149763.578462,11432.329744,223932.000000,498217.00,...,23656.00,148641.196452,244477.200323,6275.935128,1057592.00,511286.00,11342.395161,4.227932e+05,68082.334359,NaN
6,5.480000e+00,4.946537e+06,4.450000,0.32,2.140000,2.910000,3.930000,7.980000,4.970000,6.62,...,2.93,5.320000,4.240000,2.290000,4.85,2.74,8.670000,4.260000e+00,7.240000,NaN
7,6.540000e+00,4.946537e+06,8.320000,6.96,9.290000,4.880000,4.980000,8.040000,9.820000,6.87,...,10.74,6.320000,6.070000,6.070000,6.89,5.58,9.320000,6.400000e+00,8.230000,NaN
8,7.180000e+00,4.946537e+06,7.500000,8.51,9.660000,7.880000,13.020000,9.260000,7.570000,7.97,...,6.56,4.920000,6.110000,6.340000,6.94,8.74,9.940000,6.300000e+00,5.000000,NaN
9,7.930000e+00,4.946537e+06,2210.446129,10.96,3.120000,89285.554167,7.140000,10.280000,113774.803902,8.82,...,7.73,148641.196452,244477.200323,6.510000,8.79,9.53,11342.395161,7.130000e+00,8.700000,NaN
10,7.110000e+00,4.946537e+06,2210.446129,11.61,6689.537179,89285.554167,149763.578462,11432.329744,113774.803902,8.26,...,7.49,148641.196452,244477.200323,6275.935128,7.94,10.10,11342.395161,4.227932e+05,68082.334359,NaN
11,0.000000e+00,4.946537e+06,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000e+00,0.000000,NaN
0,5.786704e+06,7.818898e+06,3404.000000,339996.00,10229.000000,129354.000000,228497.000000,16930.000000,142273.000000,314619.00,...,15160.00,239227.000000,396960.000000,9742.000000,674478.00,325138.00,17419.000000,6.451300e+05,102156.000000,NaN
1,5.786704e+06,8.205908e+06,3557.000000,341335.00,10399.000000,132518.000000,236932.000000,18285.000000,148719.000000,334103.00,...,15507.00,251813.000000,410225.000000,9970.000000,705426.00,333674.00,18857.000000,6.702310e+05,109961.000000,NaN
2,5.786704e+06,8.718820e+06,3824.000000,360239.00,11235.000000,138725.000000,246915.000000,19622.000000,163187.000000,355337.00,...,17239.00,268423.000000,435163.000000,10590.000000,740623.00,349518.00,20623.000000,7.082100e+05,118129.000000,NaN
3,5.786704e+06,9.337045e+06,4214.000000,391373.00,12323.000000,149313.000000,279711.000000,21456.000000,175414.000000,382103.00,...,18349.00,280902.000000,461845.000000,11232.000000,790760.00,380514.00,22584.000000,7.531140e+05,123341.000000,NaN
4,5.786704e+06,1.008088e+07,2210.446129,434433.00,12693.000000,160724.000000,299814.000000,23729.000000,184693.000000,414964.00,...,19927.00,148641.196452,244477.200323,11948.000000,863423.00,416524.00,11342.395161,8.071040e+05,134109.000000,NaN
5,5.786704e+06,1.080365e+07,2210.446129,484930.00,6689.537179,89285.554167,149763.578462,11432.329744,198922.000000,448529.00,...,21728.00,148641.196452,244477.200323,6275.935128,933662.00,459504.00,11342.395161,4.227932e+05,68082.334359,NaN
6,5.786704e+06,4.950000e+00,4.500000,0.39,1.650000,2.450000,3.690000,8.010000,4.530000,6.19,...,2.29,5.260000,3.340000,2.340000,4.59,2.63,8.260000,3.890000e+00,7.640000,NaN
7,5.786704e+06,6.250000e+00,7.520000,5.54,8.050000,4.680000,4.210000,7.310000,9.730000,6.36,...,11.16,6.600000,6.080000,6.210000,4.99,4.75,9.360000,5.670000e+00,7.430000,NaN
8,5.786704e+06,7.090000e+00,10.200000,8.64,9.680000,7.630000,13.280000,9.350000,7.490000,7.53,...,6.44,4.650000,6.130000,6.060000,6.77,8.87,9.510000,6.340000e+00,4.410000,NaN
9,5.786704e+06,7.970000e+00,2210.446129,11.00,3.000000,89285.554167,7.190000,10.590000,113774.803902,8.60,...,8.60,148641.196452,244477.200323,6.380000,9.19,9.46,11342.395161,7.170000e+00,8.730000,NaN
10,5.786704e+06,7.170000e+00,2210.446129,11.62,6689.537179,89285.554167,149763.578462,11432.329744,113774.803902,8.09,...,9.04,148641.196452,244477.200323,6275.935128,8.13,10.32,11342.395161,4.227932e+05,68082.334359,NaN
11,5.786704e+06,0.000000e+00,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000e+00,0.000000,NaN
0,5.786704e+06,7.818898e+06,3404.000000,339996.00,10229.000000,129354.000000,228497.000000,16930.000000,142273.000000,314619.00,...,15160.00,239227.000000,396960.000000,9742.000000,674478.00,325138.00,17419.000000,6.451300e+05,102156.000000,NaN
1,5.786704e+06,8.886659e+06,3793.000000,370196.00,11617.000000,142039.000000,261327.000000,19507.000000,159431.000000,357251.00,...,16984.00,267116.000000,446835.000000,10817.000000,768951.00,363929.00,19631.000000,7.335050e+05,117264.000000,NaN
2,5.786704e+06,1.004106e+07,4424.000000,413164.00,13398.000000,160442.000000,292143.000000,22290.000000,185939.000000,404664.00,...,19778.00,301673.000000,497403.000000,12203.000000,861429.00,408887.00,23329.000000,8.376140e+05,132556.000000,NaN
3,5.786704e+06,1.110858e+07,5025.000000,469909.00,15410.000000,178479.000000,345571.000000,25061.000000,211016.000000,447435.00,...,21776.00,332999.000000,554783.000000,13318.000000,970953.00,462636.00,27484.000000,9.254370e+05,142628.000000,NaN
4,5.786704e+06,1.224287e+07,2210.446129,545638.00,17229.000000,201758.000000,382223.000000,27341.000000,233023.000000,501104.00,...,24220.00,148641.196452,244477.200323,14558.000000,1080461.00,522412.00,11342.395161,1.024222e+06,162168.000000,NaN
5,5.786704e+06,1.365352e+07,2210.446129,620974.00,6689.537179,89285.554167,149763.578462,11432.329744,256346.000000,565655.00,...,27511.00,148641.196452,244477.200323,6275.935128,1193578.00,593930.00,11342.395161,4.227932e+05,68082.334359,NaN
6,5.786704e+06,1.365000e+01,11.440000,8.88,13.570000,9.810000,14.370000,15.230000,12.060000,13.55,...,12.04,11.660000,12.560000,11.030000,14.01,11.93,12.700000,1.370000e+01,14.790000,NaN
7,5.786704e+06,1.299000e+01,16.640000,11.61,15.320000,12.960000,11.790000,14.260000,16.630000,13.27,...,16.45,12.940000,11.320000,12.820000,12.03,12.35,18.840000,1.419000e+01,13.040000,NaN
8,5.786704e+06,1.063000e+01,13.560000,13.73,15.020000,11.240000,18.290000,12.430000,13.490000,10.57,...,10.10,10.380000,11.540000,9.140000,12.71,13.15,17.810000,1.048000e+01,7.600000,NaN
9,5.786704e+06,1.021000e+01,2210.446129,16.12,11.800000,89285.554167,10.610000,9.100000,113774.803902,11.99,...,11.23,148641.196452,244477.200323,9.310000,11.28,12.92,11342.395161,1.067000e+01,13.700000,NaN
10,5.786704e+06,1.152000e+01,2210.446129,13.81,6689.537179,89285.554167,149763.578462,11432.329744,113774.803902,12.88,...,13.58,148641.196452,244477.200323,6275.935128,10.47,13.69,11342.395161,4.227932e+05,68082.334359,NaN
11,5.786704e+06,0.000000e+00,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,0.00,0.000000,0.000000,0.000000,0.00,0.00,0.000000,0.000000e+00,0.000000,NaN

In [23]:
max = eco.describe().iloc[7:8,:]
min = eco.describe().iloc[3:4,:]
max

,All_India GDP,All_India NDP,Andaman & Nicobar Islands,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Delhi,...,Puducherry,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal1
max,15251028.0,13653519.0,5721.0,699307.0,18784.0,224234.0,413503.0,30304.0,290140.0,622385.0,...,29557.0,368011.0,612194.0,16637.0,1338766.0,654294.0,29667.0,1153795.0,184091.0,NaN

In [29]:
for column in eco:
    if column == 'Duration':
        continue
    if column == 'Item Description':
        continue
    if column == 'Items  Description':
        continue
    if column == 'Items Description':
        continue
    else:
       #df[column] = (df[column] - min.iloc[0][column])/(max.iloc[0][column] - min.iloc[0][column])
        eco[column] = eco[column]/max.iloc[0][column]
eco.head()

,All_India GDP,All_India NDP,Andaman & Nicobar Islands,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Delhi,...,Puducherry,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal1
0,6.942563e-37,7.635433e-37,1.134860e-19,3.244086e-30,2.518514e-22,1.126311e-27,4.943996e-29,2.423362e-23,2.649810e-28,5.914383e-30,...,0.569002,0.724511,0.712952,0.671095,0.561327,0.549345,0.647453,0.627537,0.627532,NaN
1,7.904629e-37,7.635433e-37,1.260924e-19,3.517720e-30,2.856350e-22,1.233998e-27,5.648635e-29,2.790197e-23,2.975635e-28,6.731104e-30,...,0.638597,0.809036,0.806940,0.741600,0.639007,0.613628,0.730205,0.713214,0.716140,NaN
2,8.929797e-37,7.635433e-37,1.471410e-19,3.969769e-30,3.324175e-22,1.398262e-27,6.343451e-29,3.200547e-23,3.464765e-28,7.635122e-30,...,0.739926,0.909522,0.897920,0.833203,0.725362,0.691105,0.862676,0.818296,0.813820,NaN
3,9.881148e-37,7.635433e-37,1.631700e-19,4.501577e-30,3.815676e-22,1.558373e-27,7.480088e-29,3.595273e-23,3.939027e-28,8.471972e-30,...,0.815002,1.000000,1.000000,0.914167,0.816098,0.781267,1.000000,0.904295,0.879918,NaN
4,1.086784e-36,7.635433e-37,6.304465e-20,5.215256e-30,4.276216e-22,1.763976e-27,8.271927e-29,3.912913e-23,4.371414e-28,9.496318e-30,...,0.897689,0.403904,0.399346,1.000000,0.905810,0.879774,0.382324,1.000000,1.000000,NaN